# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/cable_delay_tester/cable_delay_tester.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cable_delay_tester || ORIG_REF_NAME==cable_delay_tester} -quiet] -quiet

# IP: bd/cable_delay_tester/ip/cable_delay_tester_rhd_spi_master_0_0/cable_delay_tester_rhd_spi_master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cable_delay_tester_rhd_spi_master_0_0 || ORIG_REF_NAME==cable_delay_tester_rhd_spi_master_0_0} -quiet] -quiet

# IP: bd/cable_delay_tester/ip/cable_delay_tester_zynq_ultra_ps_e_0_0/cable_delay_tester_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cable_delay_tester_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==cable_delay_tester_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/cable_delay_tester/ip/cable_delay_tester_clk_wiz_0_0/cable_delay_tester_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cable_delay_tester_clk_wiz_0_0 || ORIG_REF_NAME==cable_delay_tester_clk_wiz_0_0} -quiet] -quiet

# IP: bd/cable_delay_tester/ip/cable_delay_tester_proc_sys_reset_0_1/cable_delay_tester_proc_sys_reset_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cable_delay_tester_proc_sys_reset_0_1 || ORIG_REF_NAME==cable_delay_tester_proc_sys_reset_0_1} -quiet] -quiet

# IP: bd/cable_delay_tester/ip/cable_delay_tester_ila_0_0/cable_delay_tester_ila_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cable_delay_tester_ila_0_0 || ORIG_REF_NAME==cable_delay_tester_ila_0_0} -quiet] -quiet

# IP: bd/cable_delay_tester/ip/cable_delay_tester_xlconstant_0_0/cable_delay_tester_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cable_delay_tester_xlconstant_0_0 || ORIG_REF_NAME==cable_delay_tester_xlconstant_0_0} -quiet] -quiet

# IP: bd/cable_delay_tester/ip/cable_delay_tester_xlconstant_1_0/cable_delay_tester_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cable_delay_tester_xlconstant_1_0 || ORIG_REF_NAME==cable_delay_tester_xlconstant_1_0} -quiet] -quiet

# IP: bd/cable_delay_tester/ip/cable_delay_tester_xlconstant_2_0/cable_delay_tester_xlconstant_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cable_delay_tester_xlconstant_2_0 || ORIG_REF_NAME==cable_delay_tester_xlconstant_2_0} -quiet] -quiet

# IP: bd/cable_delay_tester/ip/cable_delay_tester_xlconstant_3_0/cable_delay_tester_xlconstant_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cable_delay_tester_xlconstant_3_0 || ORIG_REF_NAME==cable_delay_tester_xlconstant_3_0} -quiet] -quiet

# IP: bd/cable_delay_tester/ip/cable_delay_tester_rhs_spi_master_0_0/cable_delay_tester_rhs_spi_master_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cable_delay_tester_rhs_spi_master_0_0 || ORIG_REF_NAME==cable_delay_tester_rhs_spi_master_0_0} -quiet] -quiet

# IP: bd/cable_delay_tester/ip/cable_delay_tester_xlconstant_4_0/cable_delay_tester_xlconstant_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cable_delay_tester_xlconstant_4_0 || ORIG_REF_NAME==cable_delay_tester_xlconstant_4_0} -quiet] -quiet

# IP: bd/cable_delay_tester/ip/cable_delay_tester_xlconstant_5_0/cable_delay_tester_xlconstant_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cable_delay_tester_xlconstant_5_0 || ORIG_REF_NAME==cable_delay_tester_xlconstant_5_0} -quiet] -quiet

# IP: bd/cable_delay_tester/ip/cable_delay_tester_ila_0_1/cable_delay_tester_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cable_delay_tester_ila_0_1 || ORIG_REF_NAME==cable_delay_tester_ila_0_1} -quiet] -quiet

# IP: bd/cable_delay_tester/ip/cable_delay_tester_proc_sys_reset_1_0/cable_delay_tester_proc_sys_reset_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cable_delay_tester_proc_sys_reset_1_0 || ORIG_REF_NAME==cable_delay_tester_proc_sys_reset_1_0} -quiet] -quiet

# XDC: c:/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/cable_delay_tester/cable_delay_tester_ooc.xdc
