# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/jtag_axi_test/jtag_axi_test.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jtag_axi_test || ORIG_REF_NAME==jtag_axi_test} -quiet] -quiet

# IP: bd/jtag_axi_test/ip/jtag_axi_test_zynq_ultra_ps_e_0_0/jtag_axi_test_zynq_ultra_ps_e_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jtag_axi_test_zynq_ultra_ps_e_0_0 || ORIG_REF_NAME==jtag_axi_test_zynq_ultra_ps_e_0_0} -quiet] -quiet

# IP: bd/jtag_axi_test/ip/jtag_axi_test_jtag_axi_0_0/jtag_axi_test_jtag_axi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jtag_axi_test_jtag_axi_0_0 || ORIG_REF_NAME==jtag_axi_test_jtag_axi_0_0} -quiet] -quiet

# IP: bd/jtag_axi_test/ip/jtag_axi_test_proc_sys_reset_0_0/jtag_axi_test_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jtag_axi_test_proc_sys_reset_0_0 || ORIG_REF_NAME==jtag_axi_test_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/jtag_axi_test/ip/jtag_axi_test_clk_wiz_0_0/jtag_axi_test_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jtag_axi_test_clk_wiz_0_0 || ORIG_REF_NAME==jtag_axi_test_clk_wiz_0_0} -quiet] -quiet

# IP: bd/jtag_axi_test/ip/jtag_axi_test_ila_0_1/jtag_axi_test_ila_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jtag_axi_test_ila_0_1 || ORIG_REF_NAME==jtag_axi_test_ila_0_1} -quiet] -quiet

# IP: bd/jtag_axi_test/ip/jtag_axi_test_seeg_top_0_0/jtag_axi_test_seeg_top_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jtag_axi_test_seeg_top_0_0 || ORIG_REF_NAME==jtag_axi_test_seeg_top_0_0} -quiet] -quiet

# IP: ip/fifo_16_to_64/fifo_16_to_64.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_16_to_64 || ORIG_REF_NAME==fifo_16_to_64} -quiet] -quiet

# IP: bd/jtag_axi_test/ip/jtag_axi_test_axis_data_fifo_0_0/jtag_axi_test_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==jtag_axi_test_axis_data_fifo_0_0 || ORIG_REF_NAME==jtag_axi_test_axis_data_fifo_0_0} -quiet] -quiet

# XDC: /home/ug3/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/jtag_axi_test/jtag_axi_test_ooc.xdc
