# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ug3/Repos/ug3-seeg/ug3-seeg.srcs/sources_1/bd/jtag_axi_test/ip/jtag_axi_test_seeg_top_0_0/jtag_axi_test_seeg_top_0_0.xci
# IP: The module: 'jtag_axi_test_seeg_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/ug3/Repos/ug3-seeg/ug3-seeg.srcs/sources_1/ip/axis_data_fifo_seeg/axis_data_fifo_seeg.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_data_fifo_seeg || ORIG_REF_NAME==axis_data_fifo_seeg} -quiet] -quiet

# IP: /home/ug3/Repos/ug3-seeg/ug3-seeg.srcs/sources_1/ip/fifo_16_to_64/fifo_16_to_64.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_16_to_64 || ORIG_REF_NAME==fifo_16_to_64} -quiet] -quiet

# XDC: /home/ug3/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/jtag_axi_test/ip/jtag_axi_test_seeg_top_0_0/jtag_axi_test_seeg_top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_axi_test_seeg_top_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/ug3/Repos/ug3-seeg/ug3-seeg.srcs/sources_1/bd/jtag_axi_test/ip/jtag_axi_test_seeg_top_0_0/jtag_axi_test_seeg_top_0_0.xci
# IP: The module: 'jtag_axi_test_seeg_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/ug3/Repos/ug3-seeg/ug3-seeg.srcs/sources_1/ip/axis_data_fifo_seeg/axis_data_fifo_seeg.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axis_data_fifo_seeg || ORIG_REF_NAME==axis_data_fifo_seeg} -quiet] -quiet

# IP: /home/ug3/Repos/ug3-seeg/ug3-seeg.srcs/sources_1/ip/fifo_16_to_64/fifo_16_to_64.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_16_to_64 || ORIG_REF_NAME==fifo_16_to_64} -quiet] -quiet

# XDC: /home/ug3/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/jtag_axi_test/ip/jtag_axi_test_seeg_top_0_0/jtag_axi_test_seeg_top_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'jtag_axi_test_seeg_top_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
