# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Repos/ug3-seeg/ug3-seeg.srcs/sources_1/bd/cable_delay_tester/ip/cable_delay_tester_rst_ps8_0_99M_0/cable_delay_tester_rst_ps8_0_99M_0.xci
# IP: The module: 'cable_delay_tester_rst_ps8_0_99M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/cable_delay_tester/ip/cable_delay_tester_rst_ps8_0_99M_0/cable_delay_tester_rst_ps8_0_99M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cable_delay_tester_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/cable_delay_tester/ip/cable_delay_tester_rst_ps8_0_99M_0/cable_delay_tester_rst_ps8_0_99M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cable_delay_tester_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/cable_delay_tester/ip/cable_delay_tester_rst_ps8_0_99M_0/cable_delay_tester_rst_ps8_0_99M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cable_delay_tester_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Repos/ug3-seeg/ug3-seeg.srcs/sources_1/bd/cable_delay_tester/ip/cable_delay_tester_rst_ps8_0_99M_0/cable_delay_tester_rst_ps8_0_99M_0.xci
# IP: The module: 'cable_delay_tester_rst_ps8_0_99M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/cable_delay_tester/ip/cable_delay_tester_rst_ps8_0_99M_0/cable_delay_tester_rst_ps8_0_99M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cable_delay_tester_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/cable_delay_tester/ip/cable_delay_tester_rst_ps8_0_99M_0/cable_delay_tester_rst_ps8_0_99M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cable_delay_tester_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/cable_delay_tester/ip/cable_delay_tester_rst_ps8_0_99M_0/cable_delay_tester_rst_ps8_0_99M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cable_delay_tester_rst_ps8_0_99M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
