-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- --------------------------------------------------------------------------------
-- Tool Version: Vivado v.2023.1 (lin64) Build 3865809 Sun May  7 15:04:56 MDT 2023
-- Date        : Mon Sep 23 10:26:53 2024
-- Host        : ug3 running 64-bit Ubuntu 18.04.6 LTS
-- Command     : write_vhdl -force -mode synth_stub
--               /home/ug3/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/seeg_zynq/ip/seeg_zynq_seeg_top_0_0/seeg_zynq_seeg_top_0_0_stub.vhdl
-- Design      : seeg_zynq_seeg_top_0_0
-- Purpose     : Stub declaration of top-level module interface
-- Device      : xck26-sfvc784-2LV-c
-- --------------------------------------------------------------------------------
library IEEE;
use IEEE.STD_LOGIC_1164.ALL;

entity seeg_zynq_seeg_top_0_0 is
  Port ( 
    M_AXIS_ACLK : in STD_LOGIC;
    M_AXIS_ARESETN : in STD_LOGIC;
    M_AXIS_tdata : out STD_LOGIC_VECTOR ( 63 downto 0 );
    M_AXIS_tvalid : out STD_LOGIC;
    M_AXIS_tready : in STD_LOGIC;
    M_AXIS_tlast : out STD_LOGIC;
    S_AXI_ACLK : in STD_LOGIC;
    S_AXI_ARESETN : in STD_LOGIC;
    S_AXI_AWADDR : in STD_LOGIC_VECTOR ( 31 downto 0 );
    S_AXI_AWPROT : in STD_LOGIC_VECTOR ( 2 downto 0 );
    S_AXI_AWVALID : in STD_LOGIC;
    S_AXI_AWREADY : out STD_LOGIC;
    S_AXI_WDATA : in STD_LOGIC_VECTOR ( 31 downto 0 );
    S_AXI_WSTRB : in STD_LOGIC_VECTOR ( 3 downto 0 );
    S_AXI_WVALID : in STD_LOGIC;
    S_AXI_WREADY : out STD_LOGIC;
    S_AXI_BRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    S_AXI_BVALID : out STD_LOGIC;
    S_AXI_BREADY : in STD_LOGIC;
    S_AXI_ARADDR : in STD_LOGIC_VECTOR ( 31 downto 0 );
    S_AXI_ARPROT : in STD_LOGIC_VECTOR ( 2 downto 0 );
    S_AXI_ARVALID : in STD_LOGIC;
    S_AXI_ARREADY : out STD_LOGIC;
    S_AXI_RDATA : out STD_LOGIC_VECTOR ( 31 downto 0 );
    S_AXI_RRESP : out STD_LOGIC_VECTOR ( 1 downto 0 );
    S_AXI_RVALID : out STD_LOGIC;
    S_AXI_RREADY : in STD_LOGIC;
    RHD_CS : out STD_LOGIC;
    RHD_MOSI : out STD_LOGIC;
    RHD_SCLK : out STD_LOGIC;
    RHD_MISO1_A : in STD_LOGIC;
    RHD_MISO2_A : in STD_LOGIC;
    RHD_MISO1_B : in STD_LOGIC;
    RHD_MISO2_B : in STD_LOGIC;
    RHD_MISO1_C : in STD_LOGIC;
    RHD_MISO2_C : in STD_LOGIC;
    RHD_MISO1_D : in STD_LOGIC;
    RHD_MISO2_D : in STD_LOGIC;
    RHD_MISO1_E : in STD_LOGIC;
    RHD_MISO2_E : in STD_LOGIC;
    RHD_MISO1_F : in STD_LOGIC;
    RHD_MISO2_F : in STD_LOGIC;
    RHD_MISO1_G : in STD_LOGIC;
    RHD_MISO2_G : in STD_LOGIC;
    RHD_MISO1_H : in STD_LOGIC;
    RHD_MISO2_H : in STD_LOGIC;
    RHD_MISO1_I_P : in STD_LOGIC;
    RHD_MISO1_I_N : in STD_LOGIC;
    RHD_MISO2_I_P : in STD_LOGIC;
    RHD_MISO2_I_N : in STD_LOGIC;
    RHD_MISO1_J_P : in STD_LOGIC;
    RHD_MISO1_J_N : in STD_LOGIC;
    RHD_MISO2_J_P : in STD_LOGIC;
    RHD_MISO2_J_N : in STD_LOGIC;
    RHD_MISO1_K_P : in STD_LOGIC;
    RHD_MISO1_K_N : in STD_LOGIC;
    RHD_MISO2_K_P : in STD_LOGIC;
    RHD_MISO2_K_N : in STD_LOGIC;
    RHD_MISO1_L_P : in STD_LOGIC;
    RHD_MISO1_L_N : in STD_LOGIC;
    RHD_MISO2_L_P : in STD_LOGIC;
    RHD_MISO2_L_N : in STD_LOGIC;
    RHD_MISO1_M_P : in STD_LOGIC;
    RHD_MISO1_M_N : in STD_LOGIC;
    RHD_MISO2_M_P : in STD_LOGIC;
    RHD_MISO2_M_N : in STD_LOGIC;
    RHD_MISO1_N_P : in STD_LOGIC;
    RHD_MISO1_N_N : in STD_LOGIC;
    RHD_MISO2_N_P : in STD_LOGIC;
    RHD_MISO2_N_N : in STD_LOGIC;
    RHD_MISO1_O_P : in STD_LOGIC;
    RHD_MISO1_O_N : in STD_LOGIC;
    RHD_MISO2_O_P : in STD_LOGIC;
    RHD_MISO2_O_N : in STD_LOGIC;
    RHD_MISO1_P_P : in STD_LOGIC;
    RHD_MISO1_P_N : in STD_LOGIC;
    RHD_MISO2_P_P : in STD_LOGIC;
    RHD_MISO2_P_N : in STD_LOGIC;
    RHD_MISO1_I_DEBUG : out STD_LOGIC;
    RHD_MISO2_I_DEBUG : out STD_LOGIC;
    RHD_MISO1_J_DEBUG : out STD_LOGIC;
    RHD_MISO2_J_DEBUG : out STD_LOGIC;
    RHD_MISO1_K_DEBUG : out STD_LOGIC;
    RHD_MISO2_K_DEBUG : out STD_LOGIC;
    RHD_MISO1_L_DEBUG : out STD_LOGIC;
    RHD_MISO2_L_DEBUG : out STD_LOGIC;
    RHD_MISO1_M_DEBUG : out STD_LOGIC;
    RHD_MISO2_M_DEBUG : out STD_LOGIC;
    RHD_MISO1_N_DEBUG : out STD_LOGIC;
    RHD_MISO2_N_DEBUG : out STD_LOGIC;
    RHD_MISO1_O_DEBUG : out STD_LOGIC;
    RHD_MISO2_O_DEBUG : out STD_LOGIC;
    RHD_MISO1_P_DEBUG : out STD_LOGIC;
    RHD_MISO2_P_DEBUG : out STD_LOGIC;
    RHS_CS : out STD_LOGIC;
    RHS_SCLK : out STD_LOGIC;
    RHS_MOSI_A : out STD_LOGIC;
    RHS_MOSI_B : out STD_LOGIC;
    RHS_MOSI_C : out STD_LOGIC;
    RHS_MOSI_D : out STD_LOGIC;
    RHS_MOSI_E : out STD_LOGIC;
    RHS_MOSI_F : out STD_LOGIC;
    RHS_MOSI_G : out STD_LOGIC;
    RHS_MOSI_H : out STD_LOGIC;
    RHS_MOSI_I_P : out STD_LOGIC;
    RHS_MOSI_I_N : out STD_LOGIC;
    RHS_MOSI_J_P : out STD_LOGIC;
    RHS_MOSI_J_N : out STD_LOGIC;
    RHS_MOSI_K_P : out STD_LOGIC;
    RHS_MOSI_K_N : out STD_LOGIC;
    RHS_MOSI_L_P : out STD_LOGIC;
    RHS_MOSI_L_N : out STD_LOGIC;
    RHS_MOSI_M_P : out STD_LOGIC;
    RHS_MOSI_M_N : out STD_LOGIC;
    RHS_MOSI_N_P : out STD_LOGIC;
    RHS_MOSI_N_N : out STD_LOGIC;
    RHS_MOSI_O_P : out STD_LOGIC;
    RHS_MOSI_O_N : out STD_LOGIC;
    RHS_MOSI_P_P : out STD_LOGIC;
    RHS_MOSI_P_N : out STD_LOGIC;
    RHS_MISO_A : in STD_LOGIC;
    RHS_MISO_B : in STD_LOGIC;
    RHS_MISO_C : in STD_LOGIC;
    RHS_MISO_D : in STD_LOGIC;
    RHS_MISO_E : in STD_LOGIC;
    RHS_MISO_F : in STD_LOGIC;
    RHS_MISO_G : in STD_LOGIC;
    RHS_MISO_H : in STD_LOGIC;
    RHS_MISO_I_P : in STD_LOGIC;
    RHS_MISO_I_N : in STD_LOGIC;
    RHS_MISO_J_P : in STD_LOGIC;
    RHS_MISO_J_N : in STD_LOGIC;
    RHS_MISO_K_P : in STD_LOGIC;
    RHS_MISO_K_N : in STD_LOGIC;
    RHS_MISO_L_P : in STD_LOGIC;
    RHS_MISO_L_N : in STD_LOGIC;
    RHS_MISO_M_P : in STD_LOGIC;
    RHS_MISO_M_N : in STD_LOGIC;
    RHS_MISO_N_P : in STD_LOGIC;
    RHS_MISO_N_N : in STD_LOGIC;
    RHS_MISO_O_P : in STD_LOGIC;
    RHS_MISO_O_N : in STD_LOGIC;
    RHS_MISO_P_P : in STD_LOGIC;
    RHS_MISO_P_N : in STD_LOGIC;
    RHS_MISO_I_DEBUG : out STD_LOGIC;
    RHS_MISO_J_DEBUG : out STD_LOGIC;
    RHS_MISO_K_DEBUG : out STD_LOGIC;
    RHS_MISO_L_DEBUG : out STD_LOGIC;
    RHS_MISO_M_DEBUG : out STD_LOGIC;
    RHS_MISO_N_DEBUG : out STD_LOGIC;
    RHS_MISO_O_DEBUG : out STD_LOGIC;
    RHS_MISO_P_DEBUG : out STD_LOGIC;
    RHS_MOSI_I_DEBUG : out STD_LOGIC;
    RHS_MOSI_J_DEBUG : out STD_LOGIC;
    RHS_MOSI_K_DEBUG : out STD_LOGIC;
    RHS_MOSI_L_DEBUG : out STD_LOGIC;
    RHS_MOSI_M_DEBUG : out STD_LOGIC;
    RHS_MOSI_N_DEBUG : out STD_LOGIC;
    RHS_MOSI_O_DEBUG : out STD_LOGIC;
    RHS_MOSI_P_DEBUG : out STD_LOGIC;
    aux_signal : in STD_LOGIC
  );

end seeg_zynq_seeg_top_0_0;

architecture stub of seeg_zynq_seeg_top_0_0 is
attribute syn_black_box : boolean;
attribute black_box_pad_pin : string;
attribute syn_black_box of stub : architecture is true;
attribute black_box_pad_pin of stub : architecture is "M_AXIS_ACLK,M_AXIS_ARESETN,M_AXIS_tdata[63:0],M_AXIS_tvalid,M_AXIS_tready,M_AXIS_tlast,S_AXI_ACLK,S_AXI_ARESETN,S_AXI_AWADDR[31:0],S_AXI_AWPROT[2:0],S_AXI_AWVALID,S_AXI_AWREADY,S_AXI_WDATA[31:0],S_AXI_WSTRB[3:0],S_AXI_WVALID,S_AXI_WREADY,S_AXI_BRESP[1:0],S_AXI_BVALID,S_AXI_BREADY,S_AXI_ARADDR[31:0],S_AXI_ARPROT[2:0],S_AXI_ARVALID,S_AXI_ARREADY,S_AXI_RDATA[31:0],S_AXI_RRESP[1:0],S_AXI_RVALID,S_AXI_RREADY,RHD_CS,RHD_MOSI,RHD_SCLK,RHD_MISO1_A,RHD_MISO2_A,RHD_MISO1_B,RHD_MISO2_B,RHD_MISO1_C,RHD_MISO2_C,RHD_MISO1_D,RHD_MISO2_D,RHD_MISO1_E,RHD_MISO2_E,RHD_MISO1_F,RHD_MISO2_F,RHD_MISO1_G,RHD_MISO2_G,RHD_MISO1_H,RHD_MISO2_H,RHD_MISO1_I_P,RHD_MISO1_I_N,RHD_MISO2_I_P,RHD_MISO2_I_N,RHD_MISO1_J_P,RHD_MISO1_J_N,RHD_MISO2_J_P,RHD_MISO2_J_N,RHD_MISO1_K_P,RHD_MISO1_K_N,RHD_MISO2_K_P,RHD_MISO2_K_N,RHD_MISO1_L_P,RHD_MISO1_L_N,RHD_MISO2_L_P,RHD_MISO2_L_N,RHD_MISO1_M_P,RHD_MISO1_M_N,RHD_MISO2_M_P,RHD_MISO2_M_N,RHD_MISO1_N_P,RHD_MISO1_N_N,RHD_MISO2_N_P,RHD_MISO2_N_N,RHD_MISO1_O_P,RHD_MISO1_O_N,RHD_MISO2_O_P,RHD_MISO2_O_N,RHD_MISO1_P_P,RHD_MISO1_P_N,RHD_MISO2_P_P,RHD_MISO2_P_N,RHD_MISO1_I_DEBUG,RHD_MISO2_I_DEBUG,RHD_MISO1_J_DEBUG,RHD_MISO2_J_DEBUG,RHD_MISO1_K_DEBUG,RHD_MISO2_K_DEBUG,RHD_MISO1_L_DEBUG,RHD_MISO2_L_DEBUG,RHD_MISO1_M_DEBUG,RHD_MISO2_M_DEBUG,RHD_MISO1_N_DEBUG,RHD_MISO2_N_DEBUG,RHD_MISO1_O_DEBUG,RHD_MISO2_O_DEBUG,RHD_MISO1_P_DEBUG,RHD_MISO2_P_DEBUG,RHS_CS,RHS_SCLK,RHS_MOSI_A,RHS_MOSI_B,RHS_MOSI_C,RHS_MOSI_D,RHS_MOSI_E,RHS_MOSI_F,RHS_MOSI_G,RHS_MOSI_H,RHS_MOSI_I_P,RHS_MOSI_I_N,RHS_MOSI_J_P,RHS_MOSI_J_N,RHS_MOSI_K_P,RHS_MOSI_K_N,RHS_MOSI_L_P,RHS_MOSI_L_N,RHS_MOSI_M_P,RHS_MOSI_M_N,RHS_MOSI_N_P,RHS_MOSI_N_N,RHS_MOSI_O_P,RHS_MOSI_O_N,RHS_MOSI_P_P,RHS_MOSI_P_N,RHS_MISO_A,RHS_MISO_B,RHS_MISO_C,RHS_MISO_D,RHS_MISO_E,RHS_MISO_F,RHS_MISO_G,RHS_MISO_H,RHS_MISO_I_P,RHS_MISO_I_N,RHS_MISO_J_P,RHS_MISO_J_N,RHS_MISO_K_P,RHS_MISO_K_N,RHS_MISO_L_P,RHS_MISO_L_N,RHS_MISO_M_P,RHS_MISO_M_N,RHS_MISO_N_P,RHS_MISO_N_N,RHS_MISO_O_P,RHS_MISO_O_N,RHS_MISO_P_P,RHS_MISO_P_N,RHS_MISO_I_DEBUG,RHS_MISO_J_DEBUG,RHS_MISO_K_DEBUG,RHS_MISO_L_DEBUG,RHS_MISO_M_DEBUG,RHS_MISO_N_DEBUG,RHS_MISO_O_DEBUG,RHS_MISO_P_DEBUG,RHS_MOSI_I_DEBUG,RHS_MOSI_J_DEBUG,RHS_MOSI_K_DEBUG,RHS_MOSI_L_DEBUG,RHS_MOSI_M_DEBUG,RHS_MOSI_N_DEBUG,RHS_MOSI_O_DEBUG,RHS_MOSI_P_DEBUG,aux_signal";
attribute X_CORE_INFO : string;
attribute X_CORE_INFO of stub : architecture is "seeg_top,Vivado 2023.1";
begin
end;
