# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Repos/ug3-seeg/ug3-seeg.srcs/sources_1/ip/axis_data_fifo_seeg/axis_data_fifo_seeg.xci
# IP: The module: 'axis_data_fifo_seeg' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Repos/ug3-seeg/ug3-seeg.gen/sources_1/ip/axis_data_fifo_seeg/axis_data_fifo_seeg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_data_fifo_seeg'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Repos/ug3-seeg/ug3-seeg.srcs/sources_1/ip/axis_data_fifo_seeg/axis_data_fifo_seeg.xci
# IP: The module: 'axis_data_fifo_seeg' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Repos/ug3-seeg/ug3-seeg.gen/sources_1/ip/axis_data_fifo_seeg/axis_data_fifo_seeg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axis_data_fifo_seeg'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
