# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Repos/ug3-seeg/ug3-seeg.srcs/sources_1/bd/cable_delay_tester/ip/cable_delay_tester_ila_0_1/cable_delay_tester_ila_0_1.xci
# IP: The module: 'cable_delay_tester_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/cable_delay_tester/ip/cable_delay_tester_ila_0_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'cable_delay_tester_ila_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/cable_delay_tester/ip/cable_delay_tester_ila_0_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'cable_delay_tester_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/cable_delay_tester/ip/cable_delay_tester_ila_0_1/cable_delay_tester_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cable_delay_tester_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Repos/ug3-seeg/ug3-seeg.srcs/sources_1/bd/cable_delay_tester/ip/cable_delay_tester_ila_0_1/cable_delay_tester_ila_0_1.xci
# IP: The module: 'cable_delay_tester_ila_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/cable_delay_tester/ip/cable_delay_tester_ila_0_1/ila_v6_2/constraints/ila_impl.xdc
# XDC: The top module name and the constraint reference have the same name: 'cable_delay_tester_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/cable_delay_tester/ip/cable_delay_tester_ila_0_1/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'cable_delay_tester_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/cable_delay_tester/ip/cable_delay_tester_ila_0_1/cable_delay_tester_ila_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cable_delay_tester_ila_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
