# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Repos/ug3-seeg/ug3-seeg.srcs/sources_1/ip/fifo_16_to_64/fifo_16_to_64.xci
# IP: The module: 'fifo_16_to_64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Repos/ug3-seeg/ug3-seeg.gen/sources_1/ip/fifo_16_to_64/fifo_16_to_64.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_16_to_64'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Repos/ug3-seeg/ug3-seeg.gen/sources_1/ip/fifo_16_to_64/fifo_16_to_64_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_16_to_64'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Repos/ug3-seeg/ug3-seeg.gen/sources_1/ip/fifo_16_to_64/fifo_16_to_64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_16_to_64'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Repos/ug3-seeg/ug3-seeg.srcs/sources_1/ip/fifo_16_to_64/fifo_16_to_64.xci
# IP: The module: 'fifo_16_to_64' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Repos/ug3-seeg/ug3-seeg.gen/sources_1/ip/fifo_16_to_64/fifo_16_to_64.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_16_to_64'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Repos/ug3-seeg/ug3-seeg.gen/sources_1/ip/fifo_16_to_64/fifo_16_to_64_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_16_to_64'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Repos/ug3-seeg/ug3-seeg.gen/sources_1/ip/fifo_16_to_64/fifo_16_to_64_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_16_to_64'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
