# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ug3/Repos/ug3-seeg/ug3-seeg.srcs/sources_1/bd/seeg_zynq/ip/seeg_zynq_axi_dma_0_1/seeg_zynq_axi_dma_0_1.xci
# IP: The module: 'seeg_zynq_axi_dma_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ug3/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/seeg_zynq/ip/seeg_zynq_axi_dma_0_1/seeg_zynq_axi_dma_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'seeg_zynq_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ug3/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/seeg_zynq/ip/seeg_zynq_axi_dma_0_1/seeg_zynq_axi_dma_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'seeg_zynq_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ug3/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/seeg_zynq/ip/seeg_zynq_axi_dma_0_1/seeg_zynq_axi_dma_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'seeg_zynq_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/ug3/Repos/ug3-seeg/ug3-seeg.srcs/sources_1/bd/seeg_zynq/ip/seeg_zynq_axi_dma_0_1/seeg_zynq_axi_dma_0_1.xci
# IP: The module: 'seeg_zynq_axi_dma_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ug3/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/seeg_zynq/ip/seeg_zynq_axi_dma_0_1/seeg_zynq_axi_dma_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'seeg_zynq_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ug3/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/seeg_zynq/ip/seeg_zynq_axi_dma_0_1/seeg_zynq_axi_dma_0_1_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'seeg_zynq_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/ug3/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/seeg_zynq/ip/seeg_zynq_axi_dma_0_1/seeg_zynq_axi_dma_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'seeg_zynq_axi_dma_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
