# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/ug3/Repos/ug3-seeg/ug3-seeg.srcs/sources_1/bd/tb_seeg_top/ip/tb_seeg_top_axi_vip_0_0/tb_seeg_top_axi_vip_0_0.xci
# IP: The module: 'tb_seeg_top_axi_vip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ug3/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/tb_seeg_top/ip/tb_seeg_top_axi_vip_0_0/tb_seeg_top_axi_vip_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tb_seeg_top_axi_vip_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/ug3/Repos/ug3-seeg/ug3-seeg.srcs/sources_1/bd/tb_seeg_top/ip/tb_seeg_top_axi_vip_0_0/tb_seeg_top_axi_vip_0_0.xci
# IP: The module: 'tb_seeg_top_axi_vip_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/ug3/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/tb_seeg_top/ip/tb_seeg_top_axi_vip_0_0/tb_seeg_top_axi_vip_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'tb_seeg_top_axi_vip_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
