# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Repos/ug3-seeg/ug3-seeg.srcs/sources_1/bd/cable_delay_tester/ip/cable_delay_tester_rhd_2048_0_0/cable_delay_tester_rhd_2048_0_0.xci
# IP: The module: 'cable_delay_tester_rhd_2048_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Repos/ug3-seeg/ug3-seeg.srcs/sources_1/ip/fifo_16_to_64/fifo_16_to_64.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_16_to_64 || ORIG_REF_NAME==fifo_16_to_64} -quiet] -quiet

# XDC: c:/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/cable_delay_tester/ip/cable_delay_tester_rhd_2048_0_0/cable_delay_tester_rhd_2048_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cable_delay_tester_rhd_2048_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Repos/ug3-seeg/ug3-seeg.srcs/sources_1/bd/cable_delay_tester/ip/cable_delay_tester_rhd_2048_0_0/cable_delay_tester_rhd_2048_0_0.xci
# IP: The module: 'cable_delay_tester_rhd_2048_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: C:/Repos/ug3-seeg/ug3-seeg.srcs/sources_1/ip/fifo_16_to_64/fifo_16_to_64.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_16_to_64 || ORIG_REF_NAME==fifo_16_to_64} -quiet] -quiet

# XDC: c:/Repos/ug3-seeg/ug3-seeg.gen/sources_1/bd/cable_delay_tester/ip/cable_delay_tester_rhd_2048_0_0/cable_delay_tester_rhd_2048_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cable_delay_tester_rhd_2048_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
